#!/usr/bin/env bash
#### opiconfig - SB1 Configuration Module
#from https://www.reddit.com/r/BIGTREETECH/comments/xfom6n/comment/it32e6v/

# shellcheck enable=require-variable-braces

## Source error handling, leave this in place
set -Ee

# Set DEBIAN_FRONTEND to noninteractive
if [[ "${DEBIAN_FRONTEND}" != "noninteractive" ]]; then
    export DEBIAN_FRONTEND=noninteractive
fi

## Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap
